# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "ubuntu/trusty64"

  config.vm.define "stonecutter-journey-test", primary: true do |dev|
    dev.vm.network "private_network", ip: "192.168.50.64"
    dev.vm.network :forwarded_port, guest: 22, host: 2244, id: "ssh", auto_correct: false

    dev.vm.synced_folder "../", "/var/stonecutter-journey-test"
    
    dev.vm.provider :virtualbox do |vbox|
      vbox.customize ["modifyvm", :id, "--memory", 2048]
    end

    dev.vm.provision "ansible" do |ansible|
      ansible.playbook = "development_playbook.yml"
      ansible.inventory_path = "development.inventory"
      ansible.sudo = true
    end
  end

end

